server.ssl.enabled=true
server.ssl.key-store = ${SSL_KEYSTORE}
server.ssl.key-alias=${SSL_KEYSTORE_ALIAS}
server.ssl.key-store-type=${SSL_KEYSTORE_TYPE}
server.ssl.key-store-password=${SSL_KEYSTORE_CREDENTIAL}